version: "3.9"


services:


  # =================================================
  # MinIO Object Storage
  #
  # Used for:
  # - PDF images
  # - extracted assets
  # - multimodal RAG files
  #
  # Similar to AWS S3
  # =================================================

  minio:
    build:
      context: ./docker/minio
    container_name: rag-minio
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 10s
      retries: 5


  # =================================================
  # Qdrant Vector Database
  #
  # Used for:
  #
  # - embeddings
  # - similarity search
  # - hybrid retrieval
  #
  # =================================================


  qdrant:
    build:
      context: ./docker/qdrant
    container_name: rag-qdrant
    ports:
      # REST API
      - "${QDRANT_PORT}:6333"
      # GRPC API
      - "${QDRANT_GRPC_PORT}:6334"
    volumes:
      # Persistent vector storage
      - qdrant_data:/qdrant/storage
    restart:
      unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:6333/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 5



# =================================================
# Persistent volumes
# =================================================

volumes:
  minio_data:
  qdrant_data:


# =================================================
# Internal network
# =================================================

networks:
  default:
    name:
      rag-network